### ISSUE TITLE
Создание сайта DCCN-2023

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#1]
@timac11 
Просьба создать https://2023.dccn.ru/ по образцу прошлых лет.

### Изменения на главной странице:
1. 26th
2. 25-29 September 2023
3. Вместо кнопок Watch... и Springer... одна кнопка Register
4. Venue обновить на следующий: The DCCN-2023 conference will be held in a hybrid mode (with physical and virtual participation) in the premises of the V.A. Trapeznikov Institute of Control Sciences of Russian Academy of Sciences (ICS RAS).
Address:
[ICS RAS](https://www.ipu.ru/en/contacts), 65 Profsoyuznaya street, Moscow 117997, Russia
[View on Map](https://yandex.ru/maps/-/CCU0NJQTdA)

5. The DCCN-**2023** conference is organized under the support of the IEEE Russia Section, Communications Society Chapter (COM19).
6. Добавить в Previous Events ссылку на DCCN-2022 (https://2022.dccn.ru/)

### Изменения по структуре меню:
Оставить открытыми пока только следующие разделы:
- About (https://2023.dccn.ru/#about)
- Timeline (https://2023.dccn.ru/#timeline)
- Venue (https://2023.dccn.ru/#venue)
- Organizers & Sponsors (https://2023.dccn.ru/#committee)

### Timeline:
01 May 2023 End of papers submission. Start of peer review. End of workshop proposals submission
01 Jun 2023 End of peer review. Notification of acceptance
15 Jun 2023 Deadline for camera-ready submissions (regular papers)
01 Jul 2023  Deadline for camera-ready submissions (extended papers)
01 Sep 2023 Fee payment deadline
25 Sep 2023 Conference in Moscow
29 Sep 2023 Conference closes

**Comment by timac11** [comment]
https://dccn.ru
