### ISSUE TITLE
DCCN-2023: payment info

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#10]
@timac11 

Просьба добавить после предложения "Please note, that once the registration payment is done, no refund is available." следующую фразу + ссылку:

You can download payment details via the following link:
[DCCN2023_FEES.PDF](https://2023.dccn.ru/downloads/DCCN2023_FEES.pdf)

// Сам файл DCCN2023_FEES.pdf прикладываю
[Payment details.pdf](https://github.com/dccnconf/web23/files/12337773/Payment.details.pdf)

Просьба добавить информацию об оплате в подраздел https://2023.dccn.ru/#fees после таблицы.

**Payment information**

Payment is possible in Russian rubles by wire transfer or in cash onsite. In order to pay the registration fee follow these steps:
**Step 1.** Use the following payment details for funds transfer in Russian rubles:

<html>
<body>

Получатель (Beneficiary): | АО Научно-производственная фирма “Информационные и сетевые технологии» (АО НПФ «ИНСЕТ»)
-- | --
Юридический адрес (Address): | 129085, г. Москва, Звездный б-р, д. 19, строение 1, этаж 14, помещение I, комната 30 (оф.1415)
ИНН (Individual Taxpayer Number): | 7717647073
КПП (Industrial Enterprises Classifier): | 771701001
Р/с (Bank account number): | 40702810038090003329, ПАО "Сбербанк России" г. Москва
БИК (Bank Identification Code): | 044525225
К/с (Correspondent account): | 30101810400000000225

<p class="mt-4" style="box-sizing: border-box; border: 0px solid rgb(226, 232, 240); margin: 1rem 0px; color: rgb(0, 0, 0); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Главный бухгалтер: Котельникова Наталья Николаевна, Тел.: 8-916-688-48-93, Почтовый адрес: 117525, г. Москва, Сумской проезд, д. 31, корп. 2, кв. 80</p>
</body>
</html>

**Step 2.** 
Fill in and sign the following documents:
Agreement with an individual participant (Договор с физическим лицом): download
Act to an agreement with an individual participant (Акт с физическим лицом): download
Agreement with a legal entity (Договор с юридическим лицом): download
Act to an agreement with a legal entity (Акт с юридическим лицом): download

// @timac11 примечание: github не позволяет пересылать файлы в .doc, поэтому прикрепляю 4 файла в одном архиве
[Оплата.zip](https://github.com/dccnconf/web23/files/12334224/default.zip)

**Step 3.**
Send the scanned copies of the signed documents together with the payment confirmation to the Organizing Committee email: org@dccn.ru.

**Step 4.**
Please send the hard copies of the signed documents (договор + акт) by regular mail to the postal address of the chief accountant:  117525, г. Москва, Сумской проезд, д.31, корп.2, кв.80. Строго на имя Котельниковой Н.Н.

**ВАЖНО:**
В назначении платежа необходимо указать сумму НДС (см. таблицу оргвзносов выше), а также ФИО участника(-ов). В противном случае мы не сможем корректно отследить платеж и идентифицировать плательщика. 

В графе назначения платежа необходимо указать: “ФИО участника(-ов). Оргвзнос за DCCN2023, в т.ч. НДС (20%) — X руб."
(замените ФИО вашим полным именем, а X - суммой НДС, указанной в таблице выше).

Если Вы платите за несколько участников, просьба перечислить имена всех участников, за которых вносится оплата.

**IMPORTANT:**
In the purpose of payment, one should necessarily specify the amount of VAT (see the table of fees above), as well as the full name of the participant(s). Otherwise we will not be able to properly trace the payment and identify the payer.

Please specify in the MEMO LINE the following: “NAME SURNAME, DCCN2023 fee, incl. VAT (20%) — X RUB ”. Replace NAME and SURNAME with your full name and X with the VAT amount shown in the fees table above.

For Russian participants please indicate the name in Russian, If one person pays on behalf of a group of participants, please specify the names of all the participants.

**Comment by timac11** [comment]
done
