### ISSUE TITLE
DCCN-2023: образцы платежных поручений

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#11]
@timac11 

просьба добавить в раздел https://2023.dccn.ru/support#payment строку в конце абзаца Step 2.

Payment order templates (образцы платежных поручений): если взнос равен 10000 руб - [скачать](url), если взнос равен 1000 руб - [скачать](url), если взнос равен 8500 руб - [скачать](url). Необходимо заменить "ФИО участника" на фамилию и инициалы участника.

Ссылки [скачать](url) должны вести на соответствующие файлы в .doc, которые в github не прикрепялются, поэтому прикрепляю их единым архивом.
[платежки.zip](https://github.com/dccnconf/web23/files/12584847/default.zip)

**Comment by timac11** [comment]
done
