### ISSUE TITLE
DCCN-2023: заменить файл DCCN2023_FEES.PDF

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#12]
@timac11 просьба заменить файл [DCCN2023_FEES.PDF](https://2023.dccn.ru/downloads/DCCN2023_FEES.pdf)
на приложенный.
[Payment details.pdf](https://github.com/dccnconf/web23/files/12585149/Payment.details.pdf)

**Comment by timac11** [comment]
done
