### ISSUE TITLE
DCCN-2023: Conference schedule

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#14]
@timac11

Просьба открыть раздел Conference Schedule и заполнить его аналогично тому, как это было в прошлом году. Сетку конференции в PDF и Excel прикрепляю. Контент секций в отдельном issue #13 .

[DCCN2023_program_overview_20230919.pdf](https://github.com/dccnconf/web23/files/12663900/DCCN2023_program_overview_20230919.pdf)
[DCCN2023_program_overview_v1.xlsx](https://github.com/dccnconf/web23/files/12663901/DCCN2023_program_overview_v1.xlsx)

**Comment by timac11** [comment]
done
