### ISSUE TITLE
DCCN-2023: program update

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#15]
@timac11 

Просьба заменить программу и сетку на сайте. Новые PDF файлы прикладываю.
Причем, нужно на сайте указать, что это новая версия: DCCN2023_program.PDF -full conference program in PDF format (**updated on 23.09.2023**)

[DCCN 2023 - Программа_20230923.pdf](https://github.com/dccnconf/web23/files/12708450/DCCN.2023.-._20230923.pdf)
[DCCN2023_program_overview_20230923.pdf](https://github.com/dccnconf/web23/files/12708451/DCCN2023_program_overview_20230923.pdf)

**Comment by timac11** [comment]
done
