### ISSUE TITLE
DCCN-2023: links to online sessions

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#16]
@timac11
Просьба добавить на сайте DCCN-2023 ссылки на подключение к заседаниям (пленарное, по трекам A, B и С)

ссылки тут: 
[Links_to_sessions.pdf](https://github.com/dccnconf/web23/files/12708464/Links_to_sessions.pdf)

а также разместить инструкцию [How to use Webinar.ru](https://github.com/dccnconf/web23/files/12708469/Webinar_ru_connection_instructions.pdf)

**Comment by timac11** [comment]
done
