### ISSUE TITLE
DCCN-2023: another program update

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#17]
@timac11 
Просьба обновить программу на сайте. Изменения произошли в секциях A.2.1 (12:40 - 13:00), B.2.2 (15:10-15:30) и B.2.3. (17:20 - 17:40). 
PDF прикладываю:
[DCCN 2023 - Программа_2023096.pdf](https://github.com/dccnconf/web23/files/12729422/DCCN.2023.-._2023096.pdf)

**Comment by timac11** [comment]
done
