### ISSUE TITLE
add info about MDPI special issues

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#4]
@timac11 
Просьба в раздел https://2023.dccn.ru/#about после блока Proceedings добавить текст и 3 логотипа:

Authors of the best selected papers presented at DCCN, recommended by the Program Committee, will be invited to submit their extended papers to the Special Issues of the MDPI “Mathematics” journal (Q1, WoS, Scopus), MDPI "Sensors" journal (Q1, WoS, Scopus) and MDPI "Future Internet" journal (Q2, WoS, Scopus). All submitted manuscripts will be screened by the editorial office of the corresponding journals and peer reviewed according to the usual standards of these journals.
![image](https://user-images.githubusercontent.com/47321403/235877439-f9a4f570-03af-4d32-94a5-ee422631bc68.png)
![image](https://user-images.githubusercontent.com/47321403/235877501-67c5425e-4c8a-4943-a5bb-4098c8edc1da.png)
![image](https://user-images.githubusercontent.com/47321403/235877540-e34bb969-7a71-451d-88f7-61b65c3a47ed.png)

**Comment by timac11** [comment]
done

**Comment by kozyrevdv** [comment]
@timac11 
просьба разместить логотипы журналов в одну строку и добавить следующие ссылки для каждого логотипа, соответственно:
Mathematics: https://www.mdpi.com/journal/mathematics/special_issues/8A8D7ML512
Sensors: https://www.mdpi.com/journal/sensors/special_issues/Internet_Mobile_Things_Wireless_Sensor_Networks
Future Internet: https://www.mdpi.com/journal/futureinternet/special_issues/BY09I05QOZ
