### ISSUE TITLE
Registration & Fees

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#5]
@timac11 
Просьба открыть раздел Registration & Fees (https://2023.dccn.ru/#fees) с обновленной информацией:

### Registration & Fees

At least one author per accepted paper must pay the registration fee and present the paper in the conference session where the paper is scheduled. Please note, that once the registration payment is done, no refund is available.

Registration fees are waived for invited keynote speakers and for invited reviewers. The reviewers undertake to carefully and professionally evaluate at least 5 submitted manuscripts in an objective and impartial manner. 

PARTICIPANTS | NO IEEE MEMBERSHIP | IEEE MEMBER
-- | -- | --
Russian citizens and students of Russian universities with co-authors | 10000 RUB | 7000 RUB-15%
Students and postgraduate students of Russian universities without co-authors | 1000 RUB | 0 RUB-100%
International participants | 200 EUR | 170 EUR-15%
Listeners | Free | Free

**Comment by timac11** [comment]
done

**Comment by kozyrevdv** [comment]
@timac11 
я ошибся в цифре: вместо 7000 RUB укажи, плиз, 8500 RUB (-15%)
