### ISSUE TITLE
открыть раздел Authors + разместить шаблоны LaTeX

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#6]
@timac11 
Просьба открыть раздел https://2023.dccn.ru/authors по образцу прошлого года. Заменить только ссылки на Overleaf и архивы с шаблонами на новые.

Новые архивы:
[DCCN2023_LaTeX_RU.zip](https://github.com/dccnconf/web23/files/11409159/DCCN2023_LaTeX_RU.zip)
[DCCN2023_LaTeX_EN.zip](https://github.com/dccnconf/web23/files/11409160/DCCN2023_LaTeX_EN.zip)

Новые ссылки на Overleaf:
[Overleaf DCCN'2023 Submission Template (RUS)](https://www.overleaf.com/latex/templates/dccn2023-latex-ru/bgftzwpgkfsv)
[Overleaf DCCN'2023 Submission Template (ENG)](https://www.overleaf.com/latex/templates/dccn2023-submission-template-eng/jtfbbysddrfq)

**Comment by timac11** [comment]
done
