### ISSUE TITLE
DCCN-2023: deadlines extended

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#7]
@timac11 
Просьба обновить дедлайны на сайте https://2023.dccn.ru/#timeline
и добавить строку после заголовка:

Due to numerous requests the paper submission deadline has been extended till 01 June 2023 (HARD deadline).

01 June 2023 - End of papers submission. Start of peer review. End of workshop proposals submission
01 Jul 2023 - End of peer review. Notification of acceptance
15 Jul 2023 - Deadline for camera-ready submissions (regular papers)
01 Aug 2023 - Deadline for camera-ready submissions (extended papers)

**Comment by timac11** [comment]
done
