### ISSUE TITLE
DCCN-2023: keynote speakers

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#8]
@timac11 
Просьба открыть раздел Keynote Speakers https://2023.dccn.ru/#keynotes
и заполнить его.

Всего 4 пленарных докладчика. Пока есть полные данные о 3:

1. **Prof. Andrey Koucheryavy**,  Bonch-Bruevich St. Petersburg State University of Telecommunications, Russia
![image](https://github.com/dccnconf/web23/assets/47321403/ccf6b901-d7b7-4f9d-84b1-cd14193a71a6)

**About the speaker**
After graduating from Leningrad University of Telecommunications in 1974, A. Koucheryavy joined Telecommunication Research Institute LONIIS, where he worked till October 2003 (from 1986 to 2003 as the First Deputy Director). Dr. A. Koucheryavy holds Professor position at the Bonch-Bruevich St. Petersburg State University of Telecommunications (SUT) since 1998. There, in 2011 he became a Chaired Professor in “Telecommunication Networks and data transmission” department. Dr. A.Koucheryavy was an advisor of the Central Science Research Telecommunication Institute (ZNIIS) from 2003 to 2010. Co-founder of the International Teletraffic Seminar (1993, 1995, 1998, 2002); founder of the model network for digital networks at LONIIS (1997); co-founder of the model network for packet networks at ZNIIS (2004); co-founder of the Internet of Things Laboratory (2012) and Quality of Experience and IPTV Laboratory (2014) at SUT. Chair of the Scientific school on teletraffic theory in LONIIS (1990 – 2003); Founder and scientific school chair “Internet of Things and self-organizing networks” in SUT (2010 up to now); Steering committee member of IEEE technically co-sponsored series of conferences ICACT, NEW2AN and ICFNDS, Chair of ICACT 2020 International Steering Committee. SG11 ITU-T vice-chairman 2005 – 2008, 2009 – 2012. WP3/WP4 SG11 chairman 2006 – 2012, WP4 SG11 vice-chairman 2015-2016, Chairman of SG11 from 2016 up to March 2022. Co-founder of International Testing Center for new telecommunications technologies at ZNIIS under ITU-D competence. Host and technical program committee member of the “Kaleidoscope 2014” at SUT. Founder of the model network for telepresence services in SUT (2021). Honorary member of Popov’s society (2002).

Название доклада: **Holographic telepresence services for public communication networks**

**Abstract**
Currently, two major events are taking place in the field of networks and communication systems: the argument for the transition from network development towards increasing the generation index to integrated networks and the primary development of telepresence services.

The first direction is based on the concept of SAGSIN networks (Space-Air-Ground-Sea Integrated Networks). The creation of an integrated network in itself is very important, since it implies the unity of the network in order to optimize resources. But in addition, already in the name itself you can see the sea, and these are new tasks in the research field, since a necessary condition for the successful operation of such a network is to find solutions for the effective compatibility of networks built on the basis of radio waves and networks built on the basis of acoustic (sound) waves.

At the same time, based on the experience of mankind in the fight against the pandemic, telepresence services are acquiring new significance. Such services have existed for a long time (for example, telemedicine in the form of telephone consultations existed at the beginning of the last century), but at present there are so many potential telepresence services that it was necessary to introduce the concept of the first set of telepresence services. The report discusses the first set of telepresence services, among which special attention is paid to the provision of holographic telepresence services.

Back in 2018, a report from the Focus Group on Networks 2030 of the International Telecommunication Union assumed that services on 2030 networks would be fundamentally holographic. The Department of Telecommunication Networks and Data Transmission of St. Petersburg State University of Telecommunications started researching the issues of providing holographic services and the quality of service and quality of experience for them at about the same time. It was possible to create a model network with a transfer rate in the network core of 4Tb/s and obtain very acceptable results, which generally corresponded to the results obtained in other scientific centers in the world. However, towards the end of 2022, it became clear that while maintaining the existing initial models, holographic telepresence services would become available only to a select few, such as large corporations.

The department studies the public telecommunication networks and, naturally, the task was to create other models for the provision of holographic telepresence services that are widely available to users of public communication networks (PSTN), including universities, clinics, schools, in rural areas, etc.

To this end, as part of the work on the performance of the megagrant, an original terminal for providing holographic telepresence services was developed, the operation of which was demonstrated during the conference.

2. **Prof. Evgeny Khorov**, IITP RAS, Russia
![khorov2](https://github.com/dccnconf/web23/assets/47321403/a4ea83e3-fb67-41a8-9644-57e2b6e4943a)

**About the speaker**
Evgeny Khorov (Ph.D.'12, D.Sc.'22, IEEE Senior Member) is the Head of the Wireless Networks Laboratory of the Institute for Information Transmission Problems of the Russian Academy of Sciences (IITP RAS). Also, he is Associate Professor at MIPT, NRU HSE and MSU. His main research interests are related to 5G/6G systems, next-generation Wi-Fi, Wireless Internet of Things, and QoS-aware optimization. He has led dozens of academic and industrial projects. Being a voting member of IEEE 802.11, he contributed to the Wi-Fi 6 standard. He has authored about 200 papers, which received several Best Paper Awards. Also, he was awarded national and international prizes in science and technology. Evgeny Khorov gives tutorials and participates in panels at large IEEE events. He chaired the TPC of various IEEE and IETF conferences and workshops. In 2020, he was awarded as the Editor of the Year of Ad Hoc Networks.

Название доклада: **Towards Ultra-High Reliability of Wi-Fi 8**
**Abstract**
Traditionally, highly reliable data transmission means high probabilities of data delivery. If the delay bound is enough, it can be easily achieved  with Automated Repeat Request, i.e., retransmissions of undelivered packets. The situation changes when the delay budget is small. This issue is known as providing ultra-reliable low-latency communications in the 5G community or providing support of real-time applications in the Wi-Fi one. The system cannot retransmit undelivered packets and we need to improve reliability of every single transmission attempt. Note that in Wi-Fi networks, the main reason why the packets cannot be delivered in time is random access, interference, and traffic peaks. With the growing popularity of Cloud VR applications, online gaming and industrial automation, the requirements on delays, losses, and throughput become more challenging. In the talk, we will discuss how to satisfy them for any user, any time, and any locations. We will also consider how the Wi-Fi 8 technology - the development of which starts in 2023 - is going to address this challenge and provide such ultra-high reliability.

3. Prof. Agassi Melikov, Institute of Control Systems, National Academy of Sciences of Azerbaijan, Azerbaijan 
![image](https://github.com/dccnconf/web23/assets/47321403/57dfda38-825c-47d0-aa2d-f959d1667fc0)

**About the speaker**
Agassi Melikov received his degree in Mathematics at Baku State University, Azerbaijan in 1977, PhD in Control Theory from Institute of Automatics, Kiev, in 1984, and Doctor of Sciences in Computer Science from Department of Applied Mathematics at Kiev National Technical University, Ukraine in 1992. He completed his dissertations under the guidance of academician Volodimir Korolyuk, Ukraine. His research interests are in the tele-traffic, queuing, inventory, reliability and their applications. He has published more than 120 papers in internationally refereed journals and more than 40 presentations at the international conferences. He is the author of five monographs, including two monographs published by Springer: Performance Analysis and Optimization of Multi-Traffic on Communication Networks (2010) and Multidimensional Queueing Models in Telecommunication Networks (2014). He was a Visiting Scholar in the Telecommunication Mathematics Research Centre at the Korea University, Seoul in 2006. He is currently Head of Department of Queuing and Queuing-Inventory Systems at Institute of Control Systems, National Academy of Sciences of Azerbaijan and Head of Department of Computer Systems and Programming at National Aviation Academy, Azerbaijan.

Название доклада: **Numerical Study of Queuing-Inventory Systems with Catastrophes under Base Stock Policy**
**Abstract**
We consider a single-server queuing-inventory system (QIS) with catastrophes under the base stock policy. Consumer customers (c-customers) that arrived to buy inventory, can be form of queue in an infinite buffer. All items in the warehouse are destroyed if a catastrophe is occurring, but in such cases the c-customers in the system (on the server or in the buffer) are still waiting to be restocked. Upon arrival of negative customer (n-customer) one c-customer is pushed out, if any. A hybrid sale rule is used: if upon arrival of the c-customer, the inventory level is zero, then according to the Bernoulli scheme, this customer is either lost (lost sale rule) or it is joining to the queue (backorder rule). Mathematical model of the investigated QIS is constructed as two-dimensional Markov chain (2D MC). Ergodicity condition is established, and the matrix-analytic method (MAM) is used to calculate the steady-state probabilities of the constructed 2D MC. Formulas for performance measures are found and the results of numerical experiments are illustrated.

4. Prof. Alexander Rumyantsev, Institute of Applied Mathematical Research of Karelian Research Centre of RAS, Russia

**About the speaker**
Alexander Rumyantsev (Ph.D.'13, D.Sc.'23) is the Head of the Telecommunications Systems Laboratory and leading researcher at the Institute of Applied Mathematical Research, Karelian Research Center of the Russian Academy of Sciences; he holds professor's position at Petrozavodsk State University. His main research interests are related to queueing theory in computing systems, including parallel, distributed and quantum, as well as various performance and efficiency characteristics, including energy efficiency. He has authored over 100 papers and received several project funded by federal research support institutions. He spends time with students and schoolchildren sharing ideas in effort to intensify scientific exchange.

Название доклада: **Power and Performance in Parallel Processing**

**Abstract**
 In this talk we briefly review and summarize a few recent results in stochastic modelling of parallel processing systems, which are in fact multiserver queues of various architectures. We discuss several methods to obtain the key performance characteristics. Due to high power consumption of these systems, we consider the energy efficiency of those as well, which leads to specific models with power demand management.

**Comment by timac11** [comment]
done

**Comment by kozyrevdv** [comment]
@timac11 

Просьба добавить еще одного пленарника:
![Mohammad Hammoudeh](https://github.com/dccnconf/web23/assets/47321403/af1551a1-085f-4aab-a0c9-39c95a4e8f52)

5. Prof. Mohammad Hammoudeh, King Fahd University of Petroleum & Minerals, Saudi Arabia

**About the speaker**
Mohammad is the Saudi Aramco Cybersecurity Chair Professor at King Fahd University of Petroleum & Minerals (KFUPM). His research interest is in quantum communication technologies, quantum-safe protection methods and quantum risk assessment in both IT and OT systems. He has hands-on experience in working with quantum hardware and algorithms. Mohammad developed practical ways of thinking when evaluating the real applications of new technology such as digital twins and blockchains.

Название доклада: 
**Cybersecurity Benefits of Digital Twins for Intelligent Critical Infrastructures**
 
**Abstract**
Digital Twins technology is an area of growth for companies across a host of industries. It is poised to become the perfect partner for metaverse, virtual and augmented reality, artificial intelligence, blockchains and the internet of things to integrate physical and digital worlds with real-time interaction. This talk will take digital twin out of the abstract and highlight its real-world use cases. It will showcase digital twin capabilities to accelerate digital transformation, artificial intelligence adoption and Smart Cities strategy.
