### ISSUE TITLE
DCCN-2023: добавить НДС

### ISSUE THREAD

**Issue by kozyrevdv** [dccnconf/web23#9]
@timac11 

Просьба добавить величину НДС 20% в таблицу стоимости участия (подраздел https://2023.dccn.ru/#fees).

Registration fees below include VAT tax 20%.
<html>
<body>

PARTICIPANTS | NO IEEE MEMBERSHIP | IEEE MEMBER
-- | -- | --
Russian citizens and students of Russian universities with co-authors | **10000 RUB** (incl. VAT (20%) - 1666,67 RUB) | **8500 RUB**-15% (incl. VAT (20%) - 1416,67 RUB)
Students of Russian universities without co-authors | **1000 RUB** (incl. VAT (20%) - 166,67 RUB) | **0 RUB**-100%
International participants | **200 EUR** (incl. VAT (20%) - 33,33 EUR) | **170 EUR**-15% (incl. VAT (20%) - 28,33 EUR)
Listeners | **Free** | **Free**

</body>
</html>

**Comment by timac11** [comment]
done
